GET http://localhost:8080/recipes
###
GET http://localhost:8080/recipes/65c6f1825c7910857c0ac66b
###
GET http://localhost:8080/ingredients
###
GET http://localhost:8080/ingredients/65c6f0b75c7910857c0ac663
###
POST http://localhost:8080/recipes HTTP/1.1
content-type: application/json

{
    "name": "grilled cheese sandwich",
    "category": "sandwich",
    "prepTime": "2 min",
    "cookTime": "7 min",
    "servings": "1",
    "source": "family",
    "ingredients": [
      {"ingredient-id": "65c6fc3493bab5c230eee2c6", "quantity": "2", "uom": "slice"}, 
      {"ingredient-id": "65c6fc5f93bab5c230eee2c7", "quantity": "1", "uom": "tbs"},
      {"ingredient-id": "65c6f0b75c7910857c0ac665", "quantity": "2", "uom": "oz"}
    ],
    "directions": "Spread butter on both outer slices of bread with cheese between.  Place on hot griddle, flip when side is golden brown."
  }

###
POST http://localhost:8080/ingredients HTTP/1.1
content-type: application/json


    # {
    #   "name": "bread",
    #   "type": "bakery"
    # }
    {
      "name": "butter",
      "type": "dairy"
    }
  

###
PUT http://localhost:8080/recipes HTTP/1.1
content-type: application/json
###
DELETE http://localhost:8080/recipes HTTP/1.1
content-type: application/json
###

// production - Render
GET https://recipe-book-l98l.onrender.com/recipes
###
GET https://recipe-book-l98l.onrender.com/recipes/65c6f1825c7910857c0ac66b
###
GET https://recipe-book-l98l.onrender.com/ingredients
###
GET https://recipe-book-l98l.onrender.com/ingredients/65c6f0b75c7910857c0ac665
###
POST https://recipe-book-l98l.onrender.com/recipes HTTP/1.1
content-type: application/json

{
    "name": "french toast",
    "category": "breakfast",
    "prepTime": "5 min",
    "cookTime": "10 min",
    "servings": "6",
    "source": "family",
    "ingredients": [
      {"ingredient-id": "65c6fc3493bab5c230eee2c6", "quantity": "12", "uom": "slice"}, 
      {"ingredient-id": "65c821431498223f23276e5d", "quantity": "4", "uom": "each"},
      {"ingredient-id": "65c8216c1498223f23276e5e", "quantity": "1", "uom": "dash"},
      {"ingredient-id": "65c821811498223f23276e5f", "quantity": "1", "uom": "cup"},
      {"ingredient-id": "65c8219a1498223f23276e60", "quantity": "2", "uom": "dash"}
    ],
    "directions": "Whisk together the eggs, vanilla, cinnamon, and milk.  Dip bread slices into the egg mixture and place on a hot griddle until the egg is cook, approximately 3 minutes.  Flip and cook the other side.  Serve with syrup or powdered sugar."
  }

###
POST https://recipe-book-l98l.onrender.com/ingredients HTTP/1.1
content-type: application/json

    {
      "name": "flour",
      "type": "dry-goods"
    }
  

###
PUT https://recipe-book-l98l.onrender.com/recipes HTTP/1.1
content-type: application/json
###
DELETE https://recipe-book-l98l.onrender.com/recipes HTTP/1.1
content-type: application/json
###

{
      "name": "tomato",
      "type": "produce"
    }
put 65d0d22dd36b63fce020d197

del 65d1714ca41a5818db0fc2e9 -recipe

val - put 65c6f1825c7910857c0ac66b - number of serv
{
    "name": "tacos",
    "category": "mexican",
    "cookTime": "9 min",
    "prepTime": "5 min",
    "servings": "8",
    "source": "family",
    "ingredients": [
      {
        "ingredient-id": "65c6f0b75c7910857c0ac663",
        "quantity": "1",
        "uom": "lb"
      },
      {
        "ingredient-id": "65c6f0b75c7910857c0ac664",
        "quantity": "3",
        "uom": "tbs"
      },
      {
        "ingredient-id": "65c6f0b75c7910857c0ac665",
        "quantity": "8",
        "uom": "oz"
      },
      {
        "ingredient-id": "65c6f0b75c7910857c0ac666",
        "quantity": "12",
        "uom": "oz"
      }
    ],
    "directions": "Cook meat, add seasoning; then add toppings"
  }

post - remove type
{
    "name": "green pepper",
    "type": "produce"
  }

del 65d03847a4ad6077e6917790 - remove # from id

get 65c839f996fd9a6dd6ec179b - remove #